---
- name: Install Java and Docker
  hosts: all
  become: yes  

  tasks:
    - name: Update apt package cache (for Debian/Ubuntu).
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present
      become: yes

    - name: Install Java 8
      apt:
        name: openjdk-8-jdk
        state: present
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Install Docker dependencies
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Create keyrings directory
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Import Docker GPG key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems
    
    - name: Grant read permissions to docker.asc
      become: yes
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'  # Set the file mode to 0644 (readable by all)
        state: touch   # Ensure the file exists (create if not)


    - name: Add Docker repository
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Update apt package cache (for Debian/Ubuntu).
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Install Docker
      apt:
        name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems
