---
- name: Install Java and Docker
  hosts: all
  become: yes  

  tasks:
    - name: Update apt package cache (for Debian/Ubuntu).
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    #- name: Install Java 11
    #  apt:
    #    name: openjdk-11-jdk
    #   state: present
    #  become: yes

    #- name: Install Java 8
    #  apt:
    #    name: openjdk-8-jdk
    #    state: present
    #  become: yes
    #  when: ansible_os_family == 'Debian'  # Only run on Debian-based systems
    
    - name: Uninstall all conflicting packages.
      shell: for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do apt-get remove $pkg; done
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Update apt package cache (for Debian/Ubuntu).
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems


    - name: Install Docker dependencies
      apt:
        name: 
          #- apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Create directory for keyrings.
      shell: install -m 0755 -d /etc/apt/keyrings
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Add Docker repository
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
             sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems
    
    - name: Grant read permissions to docker.asc
      become: yes
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0644'  # Set the file mode to 0644 (readable by all)
        state: touch   # Ensure the file exists (create if not)

     
    - name: Add Docker repository
      become: yes  # Ensure privilege escalation
      apt_repository:
        repo: "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" 
        state: present
      when: ansible_distribution == 'Ubuntu' 
    #- name: Add Docker repository
    #  shell: echo \
    #          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    #          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    #          tee /etc/apt/sources.list.d/docker.list > /dev/null
    #  become: yes
    #  when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Update apt package cache (for Debian/Ubuntu).
      shell: apt update
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Install Docker
      apt:
        name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
      when: ansible_os_family == 'Debian'  # Only run on Debian-based systems
