---
- name: Install website using docker image
  hosts: all
  become: yes
  #vars:
  #  ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Giving Docker user permissions
      shell: sudo adduser docker && sudo usermod -aG sudo docker 
      become: yes
    
    #- name: wait please..
    #  shell: newgrp docker 

    - name: install python3-docker
      apt:
        name: python3-docker
        state: present
      become: yes

    #- name: Pull Docker image
    #  docker_image:
    #    name: sharagon1/web-project:1.0
    #    source: pull

    - name: Run Docker container
      docker_container:
        name: app
        image: sharagon1/web-project:1.0
        state: started
        detach: yes
        restart_policy: always
        ports:
          - "80:80"